---
- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 7 License
  become: yes
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 7
  become: yes
  apt: name={{item}} state=latest allow_unauthenticated=yes
  with_items:
    - oracle-java7-installer
    - ca-certificates
    - oracle-java7-set-default

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest allow_unauthenticated=yes
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
